Add option to allow special-use subfolders
cyrusimap/cyrus-imapd pull request #2997
Opened 2020-02-18 16:34 UTC by MichaelMenge

implement #2995 for master

2024-08-26 03:27 UTC, elliefm requested changes
Sorry this took so long to get to.  Looks good, couple of small details that need fixing though.

2024-08-26 03:27 UTC, elliefm commented on imap/mboxlist.c
> +            /* then if llowspecialusesubfolders is not enabled the target must be a single-depth mailbox too */
Typo:

```suggestion
            /* then if allowspecialusesubfolders is not enabled the target must be a single-depth mailbox too */
```

2024-08-26 03:27 UTC, elliefm commented on lib/imapoptions
> +{ "allowspecialusesubfolder", 0, SWITCH, "3.0.14" }
Don't hardcode version numbers here, just put "UNRELEASED" and the real version will be put in when a release is made.

```suggestion
{ "allowspecialusesubfolder", 0, SWITCH, "UNRELEASED" }
```

2024-08-26 15:25 UTC, MichaelMenge commented
@elliefm these changes are fine with me, can you add them or do i need to update the pull request?

2024-08-28 00:02 UTC, elliefm approved these changes
Thanks!

2024-08-28 00:02 UTC, merged