Not all systems have futimes() or TIMESPEC_TO_TIMEVAL()
cyrusimap/cyrus-imapd pull request #3174
Opened 2020-09-05 15:49 UTC by citrus-it

The `futimes()` function is not standardised and only available in Linux and some BSDs.

Check if it exists before using it, and fall back to alternatives.

The TIMESPEC_TO_TIMEVAL() macro is also not available on all platforms.

2020-09-07 01:17 UTC, elliefm requested changes
Thanks!  Visually, this looks good once the tab/space changes are made.

I can't test this on a system without these functions, but it doesn't break anything on my system with them.

2020-09-07 01:17 UTC, elliefm commented on lib/util.c
> +	if (utimes(to, tv)) {
These lines have tab characters in them, can you please convert those to 8-spaces to match the surrounding style?  Thanks.

2020-09-07 08:33 UTC, citrus-it commented
> Thanks! Visually, this looks good once the tab/space changes are made.
> 
> I can't test this on a system without these functions, but it doesn't break anything on my system with them.

I was thinking about this over the weekend, and I think `futimens()` should be preferred as that's standardised in POSIX, and also avoids the conversion between timeval and timespec.

I'll rework this later today (and fix the tabs!)

2020-09-07 08:58 UTC, citrus-it commented
Here's a new version which will use the POSIX `futimens()` function if it's available, then fallback to the non-standard `futimes()` if it is available, and finally just close the file and use `utimes()` as a last resort.

I confirmed that on OmniOS, `futimens()` is now being used, and that `config.h` looks right.

```
% grep -n UTIME config.h
147:#define HAVE_FUTIMENS 1
150:/* #undef HAVE_FUTIMES */
```

2020-09-09 00:38 UTC, elliefm approved these changes

2020-09-09 00:38 UTC, merged

2020-09-09 01:28 UTC, elliefm commented
Thanks :)

Also cherry-picked to cyrus-imapd-3.2 branch as a1f974f684, so the next stable release will include this fix.