cyrusdb_skiplist: use xsyslog for errors
cyrusimap/cyrus-imapd pull request #3309
Opened 2020-12-17 22:51 UTC by elliefm

More of this.  As usual, please try building this too, in case your compiler finds something mine didn't.  Thanks!

2020-12-18 19:53 UTC, ksmurchison commented on lib/cyrusdb_skiplist.c
> +        xsyslog(LOG_ERR, "DBERROR: retry_writev failed", NULL);
I think we can use db->fname here

2020-12-18 19:53 UTC, ksmurchison commented on lib/cyrusdb_skiplist.c
> +            xsyslog(LOG_ERR, "DBERROR: retry_write failed", NULL);
I think we can use db->fname here

2020-12-18 19:55 UTC, ksmurchison requested changes
This looks good (pending my 2 inline comments) and compiles cleanly for me

2020-12-28 23:43 UTC, elliefm commented
Thanks.  I've updated those two lines to log the db->fname.  Trivial changes, but we're also not in any hurry here... can you give it another compile check once you're back from break, just in case?

2021-01-18 01:22 UTC, brong commented
Gonna add this to our build, assuming that's all happy we'll merge it :)

2021-02-09 00:24 UTC, merged

2021-02-09 07:55 UTC, rsto reviewed
Looks good to me.