cyrusdb_twoskip: use xsyslog for errors
cyrusimap/cyrus-imapd pull request #3349
Opened 2021-02-09 01:19 UTC by elliefm

More of this.  Please try to build it, in case your compiler finds stuff mine doesn't.

There's a couple of log lines where I'm not sure what the variables being logged represent, which makes it hard to name them well.  I've annotated these with XXX comments, guidance would be appreciated!

2021-02-09 07:54 UTC, rsto commented
Builds cleanly for me with gcc 8.3.0

2021-02-09 12:43 UTC, ksmurchison commented on lib/cyrusdb_twoskip.c
> +                /* XXX semantically, what is "i" here? */
Looks like "i" is record.level

2021-02-09 12:44 UTC, ksmurchison commented on lib/cyrusdb_twoskip.c
> +            /* XXX is "offset" correct? */
I think "i" is level again

2021-02-09 12:45 UTC, ksmurchison approved these changes
Compiles cleanly with GCC 10.2.1

2021-02-26 05:30 UTC, brong requested changes
Just changing 'i' to level will be good - otherwise looks great

2021-02-26 05:30 UTC, brong commented on lib/cyrusdb_twoskip.c
> +                                 FNAME(db), (LLU)record.offset, i, (LLU)fwd[i]);
Yep, as Ken said - it should be `level=<%d>`  ... `i`.

2021-02-26 05:30 UTC, brong commented on lib/cyrusdb_twoskip.c
> +                             FNAME(db), (LLU)fwd[i], i);
Ditto, `level=`

2021-02-28 23:56 UTC, elliefm commented
Updated those `i=<%d>`'s to `level=<%d>`

2021-02-28 23:59 UTC, merged