Jmap shared upload collection
cyrusimap/cyrus-imapd pull request #3448
Opened 2021-04-06 20:02 UTC by ksmurchison

2021-04-12 12:18 UTC, rsto requested changes
The logic looks sane to me. Found two nits that I think would make the code clearer to read.

2021-04-12 12:18 UTC, rsto commented on imap/http_jmap.c
> +static int sharedrights_cb(const mbentry_t *mbentry, void *vrock)
Nit: Rename this to has_shared_rw_rights_cb ? This function really just that boolean question, and it's less confusing to than having the same named function to different things in two files.

2021-04-12 12:18 UTC, rsto commented on imap/jmap_api.c
> +        /* XXX This is currently done by brute force.
This comment might be better placed at the start of set_upload_rights. Without knowing the internals of that function, it is not clear where the "brute force" is coming from here.

2021-04-12 17:41 UTC, merged

2021-04-14 03:14 UTC, elliefm commented
Does this need to be backported to 3.4?  The Cassandane test now checks for 3.4 or greater, but 3.4 doesn't currently have this code, so the test runs and fails.  Not sure whether the test is correct and the changes need to be backported, or if they don't and the test's version check is wrong.

It's not clear to me what the big picture of this change is or how it fits into other JMAP stuff that's happened on master (and not 3.4)

2021-04-14 11:39 UTC, ksmurchison commented
This should probably be backported if we support sharing of JMAP resources in 3.4, which I assume we do.

2021-04-14 23:24 UTC, elliefm commented
The calendar_set_sharewith test previously worked before the specifics for this PR were added to it, so I'm concluding from that that it does support sharing, and therefore this needs to be backported.  Cool, thanks for the clarification, I'll get it done. :)

2021-04-15 00:24 UTC, elliefm commented
This is now on 3.4