Typos
cyrusimap/cyrus-imapd pull request #3506
Opened 2021-05-27 08:57 UTC by dilyanpalauzov

2021-05-28 00:09 UTC, elliefm approved these changes

2021-05-28 10:04 UTC, rsto requested changes
Thanks for fixing these typos, @dilyanpalauzov 

However, I do request to change the commit message. We can talk about the pros and cons of DCOs, but the commit history isn't the right place to do this. Could you please remove you arguments against DCOs from the commit?

If you would like to share your arguments, please do it on the cyrus development list where we can have a discussion.

2021-06-23 14:16 UTC, kanarip commented
At the very least, the typo in 'presense' should be fixed, or this merge request is ironically self-defeating.

2024-09-11 16:30 UTC, ksmurchison approved these changes

2024-09-11 16:32 UTC, ksmurchison approved these changes

2024-09-11 16:32 UTC, merged