http_jmap.c: initial implementation of proxying JMAP (based on authenticated user)
cyrusimap/cyrus-imapd pull request #3548
Opened 2021-07-10 14:19 UTC by ksmurchison

Each JMAP method should probably be proxied by accountId, but this is a start.

2021-07-12 05:56 UTC, rsto reviewed
The code changes look sane to me. Two questions, though:

- Will this work with web sockets, too?
- Has this been tested? I guess we don't have automated tests for proxying JMAP, so I assume you did manual testing?

2021-07-12 10:49 UTC, ksmurchison commented
This currently will not work with WebSockets.
I only tested it by hand.

2021-07-12 10:53 UTC, rsto commented
OK, I can't tell if not supporting WebSockets is good enough, but the code at hand looks sane. I'll approve.

2021-07-12 10:53 UTC, rsto approved these changes
Looks good to me.

2021-07-13 15:09 UTC, ksmurchison commented
Updated to proxy JMAP/WS over HTTP/1.1.  JMAP/WS over HTTP/2 still to be done

2021-07-14 00:29 UTC, elliefm commented
I'd like to see at least a basic cassandane test for this.  We already have the Murder test suite which knows how to set up a frontend/mupdate server and a couple of backends, so the infrastructure work is already done.

A copy of Murder.frontend_commands that uses JMAP instead of IMAP would be a great start, just so we can establish the baseline of "stuff is proxied to the right place, responses come back, actions take effect, and we'll notice if it breaks later"

2021-07-14 06:33 UTC, rsto requested changes
The code looks good me, except for using syslog. I agree with @elliefm that we it needs at least a basic Cassandane test. Also, I think this feature warrants an entry in the changes directory.

2021-07-14 06:33 UTC, rsto commented on imap/http_jmap.c
> +            syslog(LOG_ERR, "mlookup(%s) failed: %s", inbox, error_message(r));
could use xsyslog here

2021-07-20 16:29 UTC, closed without merging