No more strlist
cyrusimap/cyrus-imapd pull request #3697
Opened 2021-10-04 10:03 UTC by brong

Gonna ask both of you to review this.  Ken because you were the major user of strlist throughout the HTTP code, and ellie because you've been doing lots of really careful review and I appreciate it :)

There's two commits here - the first turns tok_next into a thing that returns a 'const char *', because mostly that's all we need, and it reminds us not to free or screw with it.  The couple of places that do make changes can then be much more carefully reviewed.

The second commit replaces 'struct strlist' with a strarray_t in the couple of places that it was being used.  It largely impacts the query arg parsing code and the timezone code.

This work is based on top of https://github.com/cyrusimap/cyrus-imapd/pull/3626 at which time strlist became a very boring type.

2021-10-04 15:21 UTC, ksmurchison approved these changes
LGTM

2021-10-06 03:49 UTC, elliefm requested changes
Couple of small-but-scary things that look like typos (comments inline).  Both in http_tzdist.c, curiously, so maybe we don't have enough test coverage for that module.

More concerningly, cunit/tok.testc doesn't build.  At a glance, it looks like it's all just complaints about the API changing to `const char *` and the tests not having been updated to match yet.

Though: when I run Cassandane across this, I get core files left behind from `JMAPCore.eventsource`, `JMAPTestSuite.t:core:download`, and `JMAPTestSuiteWS.t:core:download`.  They're all "double free or corruption" during httpd `transaction_free()`, or something like that (I've lost my terminal scrollback, whoops).

For whatever it's worth, I built and tested this with the branch rebased on top of current master (9c128d0a26), and with Cassandane at ec84f488.  The failing tests are fine without this PR on top -- so perhaps there's something subtly wrong with the tok changes, and the problem is being masked by the trivial testc build problems?  I'm not sure.  I don't see anything wrong by eye, other than the http_tzdist things I already mentioned.

2021-10-06 03:49 UTC, elliefm commented on imap/http_tzdist.c
> +        latitude = strtod(val, &endptr);
Lost a `+4` here?  Looks like we were trying to skip over "geo:"

2021-10-06 03:49 UTC, elliefm commented on imap/http_tzdist.c
> +        if (strarray_size(param) != -1) {  /* once only */
`-1`??

2024-09-16 01:47 UTC, elliefm commented
@brong Still want this?  No longer merges, but my review at the time reckoned there were a bunch of broken tests anyway.  If we wanna keep it, it'll need a rebase and some attention.

2024-10-08 23:50 UTC, closed without merging

2024-10-09 15:54 UTC, brong commented
Yeah, I don't care enough to restore this :)