cyr_expire: add config options to control expunging
cyrusimap/cyrus-imapd pull request #3866
Opened 2022-01-13 22:16 UTC by brong

1) expire_by_savedate (default true)

If set, check the savedate rather than gmtime on records to decide
whether to expunge them

2) expire_keep_flagged (default false)

If set, never expunge messages with the \Flagged system flag set.

2022-01-13 22:58 UTC, elliefm requested changes
Unreleased imapd.conf option changes shouldn't have a version number, they should have "UNRELEASED" -- the release manager (me) will fill them in appropriately when they make it into some actual release

It looks like the default expiry calculation behaviour is changing?  This will need to be remarked in release notes eventually, which means there needs to be a changes/next file for this PR so that that detail doesn't get forgotten over the coming year.

2022-01-13 22:58 UTC, elliefm commented on lib/imapoptions
> +{ "expire_by_savedate", 1, SWITCH, "3.7.0" }
This needs to be the string "UNRELEASED", not "3.7.0"
```suggestion
{ "expire_by_savedate", 1, SWITCH, "UNRELEASED" }
```

2022-01-13 22:58 UTC, elliefm commented on lib/imapoptions
> +{ "expire_keep_flagged", 0, SWITCH, "3.7.0" }
Ditto
```suggestion
{ "expire_keep_flagged", 0, SWITCH, "UNRELEASED" }
```

2024-10-02 18:18 UTC, ksmurchison commented
@brong do we still want this functionality or should we close this PR?

2025-01-15 04:01 UTC, brong commented
@ksmurchison I think we do want this behaviour!  Then we can use cyrus's built in expunging rather than what we do now, which is use SAVEDATE in a external script.

2025-03-17 06:22 UTC, brong commented
@elliefm I have fixed imapoptions and made a changes file, and also made the default keep the old behaviour

2025-03-19 02:26 UTC, elliefm approved these changes
Looks good, thanks

2025-04-10 17:40 UTC, merged

2025-04-11 04:01 UTC, dilyanpalauzov commented
The text in the PR says the defaults are for expire_by_savedate → true, and for expire_keep_flagged → false.  changes/next/cyr-expire-options says for both the default is false.  The lines:
 
 > { "expire_by_savedate", 0, SWITCH, "UNRELEASED" }
 > { "expire_keep_flagged", 0, SWITCH, "UNRELEASED" }
 
suggest that for both options the default is false.  But for the former the documentation states the opposite:
 
 > /* If true, calculate age of messages for expiry by the savedate (timestamp when the message was added to this folder) rather than gmtime (date header on the message).  Default is true. */
 
 I suggest removing the text “The default is … ” in imapoptions for both options, as in most cases there is no need to spell the default values there.  The reason is that the rendered documentation includes the default value anyway, cf. https://www.cyrusimap.org/imap/reference/manpages/configs/imapd.conf.html for allowapop: and allowdeleted:.
 
 Moreover, for binary option I do not think that the spelling “If true" or "If set” is necessary in the documentation.  It is good enough to spell what the option does, it is obvous from the context that the option does that thing only when it is enabled.