IMAP search and JMAP queries complexity fix attempt
cyrusimap/cyrus-imapd pull request #4121
Opened 2022-06-03 22:13 UTC by mildred

See #4111 where I investigated a simple JMAP query expression that should not be very complex trigger complexity limits, probably because the normalization process eat a great many nodes. These two commits are an attempt at fixing it.

It is currently not tested because I do note yet have the development environment. Also I would have liked to write some tests to validate it works, but I have no idea how the test suite is working. I'd also like to test it on a server with real data to see if the queries now work.

-   [search] Remove trivial nodes during the normalization process
    
    When normalizing a search expression, the normalizing process can
    generate too many nodes for the complexity limit while in fact the
    normalized expression is quite simple. To overcome this, we reduce
    the nnodes complexity when a node is freed, and if too many nodes are
    created during a pass of the normalization process, a cleaning pass is
    performed on the search tree.

-   [jmap] Improve query of the NOT operator
    
    The JMAP NOT operator was translated to a NOT(OR(..., ...)) search
    expression instead of a AND(NOT(...), NOT(...)). The process of
    normalizing search expressions forces the second form. Providing the
    search expression already in the correct order removes complexity from
    the normalization process, and can help not reaching the complexity
    limit.

cc @rsto

2022-06-06 15:53 UTC, rsto requested changes
This all looks promising, thanks.

But: I ran the code with the first commit (that detrivializes the search tree regularly) and it segfaults out on a couple of our tests. I dug into the core dump of the Cassandane test `JMAPEmail.email_query_dnfcomplexity` and the crash is caused by reading a nullptr at `has_enough_children (search_expr.c:521)` (from `normalise (search_expr.c:734)`). I tried to debug, but haven't yet found the root cause.

Are you in the process of setting up a test environment for Cassandane? If so, a guide for setting it up is at http://www.cyrusimap.org/imap/developer/developer-testing.html. If you run into any issues while doing so, please let me know.

2022-06-07 19:46 UTC, mildred commented on imap/jmap_mail.c
> +            this = search_expr_new(parent, SEOP_AND);
I'm not entirely sure what `NOT(a,b,c)` means in the Cyrus source code. in JMAP it is defined as `NOT a AND NOT b AND NOT c` but it is the same here? If so, why did the previous implementation used `NOT(OR(a,b,c))` and not `NOT(a,b,c)`.

2022-06-07 20:31 UTC, mildred commented
Thank you for your review and the two mistakes I made. I haven't found the time to set up the environment properly yet. I'm still compiling cyrus, it should work but I have limited time.

The segfault is probably caused by the fact that I added a call to detrivialise at the startup of the normalize routine. The next call is  a call to `has_enough_children(*ep)`. If `*ep` is NULL, it must mean that detrivialise set it to NULL. Perhaps it can happen in a few cases where the `*op` node is removed and freed.

I drafted a new commit, I don't even know if it compiles yet, that will restart the nornmalize process from the root if detrivialise is called. It has the advantage of detrivialising the complete expression from the root and track a global last nnodes collection variable.

2022-06-08 08:14 UTC, rsto commented
> The next call is a call to has_enough_children(*ep). If *ep is NULL, it must mean that detrivialise set it to NULL. Perhaps it can happen in a few cases where the *op node is removed and freed.

Yeah, I came to notice but have not yet found out when that happens. Valgrind did not help with this either. I will recompile and test on my local build later, maybe I can identify where the NULL pointer comes from.

2022-06-09 11:19 UTC, rsto commented
The `this` variable is unitialized, I just compiled with `-Wall -Werror`. I fixed this locally and ran the tests, but it keeps erroring out. I think the approach of this PR is going in the right direction, but I need to take more time to build, test and adapt.

2022-06-22 19:54 UTC, mildred commented
Fixed the `this` variable being uninitialized reverting to the previous behaviour (SEOP_UNKNOWN). Perhaps we should error out instead, I don't believe there are legitimate use cases.

2022-06-22 21:55 UTC, mildred commented
Testing my patches against version 3.4.3 it seems to work for the complexity issue : https://github.com/mildred/cyrus-imapd/releases/tag/3.4.3-jmap-complexity-fixes

I have a problem however when in JMAP I have a NOT node with an empty list condition. I get an invalidArguments error now.

In JMAP, NOT is defined by

> NOT: None of the conditions must match for the filter to match.

if there is no condition, the NOT node can be set to TRUE instead.

2022-06-22 22:45 UTC, mildred commented
The last commit does not seem to fix the invalidArguments error...

2022-06-23 09:46 UTC, rsto commented
I just created PR for your pull feature branch that fixes the "invalidArguments" error. Please report back if this helps with your testing, and if it's all good pull it in your PR. Also: version 3.4 is unsupported.

2022-06-23 23:36 UTC, mildred commented
Thank you for https://github.com/mildred/cyrus-imapd/pull/1
I use version 3.4 because this is what is shipped by debian stable backports (bullseye-backports) that is installed on the server where I make my tests

2022-06-24 00:10 UTC, mildred commented
That version is perfect, I have no more issues.

2022-06-24 00:18 UTC, elliefm commented
> Also: version 3.4 is unsupported.

This is incorrect.  3.4 is the current stable version, and will be so until 3.6 gets out of beta.

2022-06-24 07:01 UTC, rsto commented
> > Also: version 3.4 is unsupported.
> 
> This is incorrect. 3.4 is the current stable version, and will be so until 3.6 gets out of beta.

Sorry, my bad. I always work with the development branch so I lost track of the current stable release.

2022-06-24 07:04 UTC, rsto commented
> That version is perfect, I have no more issues.

Great! I hope you can keep on using your fork for some time? I do plan to merge this into master, but I first need to vet the code again and thoroughly test it.

2022-06-24 12:18 UTC, mildred commented
No problem, I didn't expect a fix to reach debian in any reasonable time frame anyway

2022-07-21 14:46 UTC, rsto commented
@mildred Thanks again for the patches. I have reworked the commits a bit and tested them on my build systems. I have created a new branch which includes your changes: https://github.com/cyrusimap/cyrus-imapd/commits/mildred-shanti-jmap-complexity-fixes

I did one change in the normalization logic, which is that instead of aborting for doubles nnodes count at root, we let the complexity check decide: https://github.com/cyrusimap/cyrus-imapd/commit/7b4d8b612dc7a116de50bad240e78679f39444b1
 I think this is a reasonable approach, butI would appreciate if you would find time to also test the branch and make sure it also fits with your requests. After this, I plan to merge it into the main branch if no further issues show up.

2022-09-19 15:23 UTC, rsto commented
@mildred thanks again. This now deployed on Cyrus main branch at https://github.com/cyrusimap/cyrus-imapd/commit/1cf725f905f1e54c5f5c1d9a837812bc43abb2c0

2022-09-19 15:23 UTC, closed without merging