jmap: option to allow relaxed IDs in createdIds
cyrusimap/cyrus-imapd pull request #4239
Opened 2022-09-21 04:00 UTC by brong

This was lying around on my desktop - it seems it might be generally useful to merge.

2022-09-21 05:58 UTC, rsto reviewed
I don't think this is right. The commit message currently tells the truth, because jmap_is_valid_id only is called within jmap_api.c for creation ids. But as soon as we use jmap_valid_id somewhere else it might accept invalid regular JMAP ids (we already have a copy of the jmap_valid_id code in jmap_ical.c for stupid linkage reasons, but we might refactor it to link to jmap_api).
I suggest we either introduce `jmap_is_valid_creation_id` or parametrize `jmap_is_valid_id`.

2024-10-08 23:22 UTC, elliefm requested changes
(Changes requested as per @rsto's review)

2024-10-08 23:24 UTC, elliefm commented
@brong Do you still think this is useful? Robert thought it needed work, and it no longer applies cleanly so it'll need a rebase at least.

2024-10-13 23:59 UTC, robmueller commented
As an FYI, I believe at the moment cyrus uses the uid from the iCal data for the CalendarEvent jmap id and the calendar path component for the Calendar jmap id. Neither of these have to conform to RFC8620 section-1.2, so cyrus can (and does) return invalid jmap id's. It feels problematic that an id returned from cyrus can't then be used in the createdIds map passed back in to cyrus.

2024-10-14 06:46 UTC, rsto commented
> As an FYI, I believe at the moment cyrus uses the uid from the iCal data for the CalendarEvent jmap id and the calendar path component for the Calendar jmap id. Neither of these have to conform to RFC8620 section-1.2, so cyrus can (and does) return invalid jmap id's.

That is correct for JMAP calendar ids, it is in general not correct for calendar event ids. For the latter, Cyrus encodes the UID in base64 if the original UID value is not a valid JMAP id. However, an excessively long UID value where either its original or base64-encoded representation exceed the 255 octet limit would render it invalid again.

> It feels problematic that an id returned from cyrus can't then be used in the createdIds map passed back in to cyrus.

I very much agree. I think the answer is to make Cyrus only return valid identifiers for all JMAP object types, rather than relaxing creation ids. This will take time to implement, though, so if there currently is an issue with invalid ids, we might indeed want to relax id validation.

2025-01-15 03:59 UTC, brong commented
We're taking a different approach to IDs, this is now not needed

2025-01-15 03:59 UTC, closed without merging