IMAP IDLE & NOTIFY
cyrusimap/cyrus-imapd pull request #4403
Opened 2023-02-10 21:38 UTC by ksmurchison

IMAP IDLE rewrite with an eye towards implementing IMAP NOTIFY (RFC 5465) and unsolicited LIST responses for IMAP4rev2.

2023-02-13 00:33 UTC, elliefm commented
This is failing a load of cassandane tests on CI.  Do you expect that, and want me to get started reviewing anyway, or should I hold off until you've had a chance to sort it out?

2023-02-13 00:38 UTC, ksmurchison commented
Hold off. I haven't run Cass yet. It's probably something stupid or a bad test

2023-03-03 02:23 UTC, elliefm reviewed
Did a partial read of this, found one nit but generally looks okay so far.  Stepping away cause I'm losing focus, need to come back to it again later.

2023-03-17 15:51 UTC, brong requested changes
I think we should lowercase `mailboxid` over the wire.  Otherwise looks great.

2023-03-17 15:51 UTC, brong commented on imap/idled.c
> +        json_string_value(json_object_get(nrock->msg, "mailboxID"));
we should probably make this all lowercase - that's what JSON API users are used to, and maybe there will be pluggable IDLE engines

2023-03-20 12:54 UTC, ksmurchison commented on lib/sqldb.c
> +            buf_printf(&buf, "<%lu bytes>", buf_len(&bval->val.b));
Yep.  Done

2023-03-20 20:05 UTC, brong commented on imap/idled.c
> +        json_string_value(json_object_get(nrock->msg, "mailboxID"));
Legit

2023-03-20 20:06 UTC, brong approved these changes
Yeah, I approve of this

2023-03-20 20:43 UTC, merged