charset.c: extract URLs and "alt" text from HTML
cyrusimap/cyrus-imapd pull request #4425
Opened 2023-03-07 10:37 UTC by rsto

This updates HTML to plain text extraction to preserve the values of the HTML anchor tag "href" attribute, as well as the HTML img tag "src" and "alt" attributes.

The value of the "href" and "src" attributes is enclosed in angle brackets. It is emitted at the end of the HTML tag, such as:

     <a href="https://example.com">Click here</a>

     Click here <https://example.com>

The value of the img "alt" attribute is surrounded by round brackets and follows the value of the "src" attribute, separated by a single space. An "alt" attribute without a "src" attribute is ignored.  For example:

     <img alt="A cat" src="cat.png"/>

     <cat.png> (A cat)

This change only applies to attribute values that are enclosed either by double or single quotes. Unquoted attribute values remain ignored.

2023-03-07 14:16 UTC, ksmurchison approved these changes
LGTM

2023-03-07 23:23 UTC, elliefm requested changes
This fails to build for me under `-Werror` because of a mixed-signedness comparison warning.  It's curious that it built okay under CI, I thought we were using `-Werror` there too.

It builds cleanly and passes all tests with the change I've suggested inline

2023-03-13 14:11 UTC, rsto commented on lib/charset.c
> +        char quot;
done. thanks.

2023-03-15 00:05 UTC, elliefm approved these changes

2023-04-11 11:24 UTC, merged