imap/httpd: remove DIGEST-MD5
cyrusimap/cyrus-imapd pull request #4680
Opened 2023-10-07 16:41 UTC by dilyanpalauzov

DIGEST-MD5 is declared Historic by RFC 6331 and is removed from Cyrus SASL by https://github.com/cyrusimap/cyrus-sasl/commit/2ce03b618ad60338e8f9094f5b7ba7ee0aef40bf.

2023-10-07 17:41 UTC, dilyanpalauzov commented
In docsrc/imap/rfc-support.rst I have replaced RFC 7615 with RFC 9110 under “RFC 2617 updated by…“, as the latter replaces the former.

docsrc/assets/man-imtest.rst does still mention the paramters `--realm` and `--reauth-attempts` but does not mention mechanisms, which use these parameters.

2024-01-03 13:58 UTC, ksmurchison requested changes
This looks complete and correct.  I have just one comment, and once fixed, I will approve.

2024-01-03 13:58 UTC, ksmurchison commented on imap/httpd.h
>      AUTH_SPNEGO       = (1<<2),
Can you update this PR to either add a comment that (1<<1) was deprecated, or adjust the values for AUTH_SPNEGO, etc?  Having values of the enum jump from (1<<0) to (1<<2) with now explanation would look weird.

2024-03-17 00:21 UTC, ksmurchison approved these changes

2024-03-17 00:21 UTC, merged