Rename between users
cyrusimap/cyrus-imapd pull request #4758
Opened 2023-12-02 11:14 UTC by brong

We found an issue in Fastmail production where a user had done:

1) `rename user.A.foo user.B.foo`

followed by

2) `rename user.B.foo user.A.foo`

Which had caused conversations to be all broken because we weren't correctly detecting this case in the mailbox_rename_nocopy (uuid paths) case.

This PR adds a test for the case, then code to make it work (and yes, I did tdd this!)

2023-12-02 14:19 UTC, ksmurchison requested changes
The code looks sane to me, but its failing CI

2023-12-12 11:49 UTC, brong commented
CI is fully passing now on my machine (including JMAP-Tester, I added that)

2023-12-12 13:24 UTC, ksmurchison approved these changes
This all looks sane to me, and if it works, it works

2023-12-22 03:39 UTC, brong commented
@elliefm I've added backport tags to this - it fixes an otherwise bad bug that came in with uuid mailboxes

2024-02-12 00:41 UTC, merged

2024-03-04 04:06 UTC, elliefm commented
This doesn't backport well to 3.6, because the test Quota.storage_convquota_immediate relies on the `userrawquota` annotation, which doesn't exist yet.  I guess that's why @brong didn't tag this for 3.6 initially?

If we do want to backport this to 3.6, we'll either also need #4203 and #4209 (at least), or need to drop this test