misc: fix warnings with -O3
cyrusimap/cyrus-imapd pull request #4975
Opened 2024-07-15 03:35 UTC by elliefm

There's a bunch of compiler warnings that aren't detected unless certain optimisations are being performed.  This PR fixes the warnings that turn up for me using GCC 12.2.0-14 on Debian Bookworm when compiling with `-O3` in CFLAGS and CXXFLAGS.  If you have a newer compiler to try with, it might find more.

2024-07-15 03:46 UTC, elliefm commented
Back to draft, gonna fix some that turn up with `-D_FORTIFY_SOURCE` too while I'm in here

2024-07-15 06:36 UTC, rsto commented
I'm using the same compiler version.

2024-07-15 11:49 UTC, ksmurchison commented
I will test against GCC 13.3.1 and 14.1.1

2024-07-15 13:43 UTC, ksmurchison requested changes
Need to add the diff that I supplied

2024-07-16 23:32 UTC, elliefm commented
Thanks!

2024-07-19 00:43 UTC, elliefm commented
I thought I was going to fix these warnings and then work on the actual problem separately, but the two wound up entangled and it no longer makes sense to keep them separate, so I'm closing this one off.

This work, as well as the actual bug fix, are now in #4980

2024-07-19 00:43 UTC, closed without merging