xunlink: clear errno on ENOENT
cyrusimap/cyrus-imapd pull request #5184
Opened 2024-12-23 00:14 UTC by elliefm

We always ignore this case anyway.  Swallowing it here stops it polluting unrelated xsyslog lines later

2025-02-12 12:39 UTC, ksmurchison approved these changes
I like it

2025-02-12 22:32 UTC, rjbs approved these changes
I am not reviewing the specific code, but we discussed this conceptual change and I agreed it was a good one.

2025-02-13 16:04 UTC, wolfsage requested changes
I'm confused by a few of the changes, it seems we'll no longer log on ENOENT when we would before. Is that really intentional?

2025-02-13 16:04 UTC, wolfsage commented on imap/append.c
> -        if (xunlink(p) != 0) {
Here ENOENT would cause a log failure, now it doesn't. Are we sure we don't want to know if the file didn't exist in this case?

2025-02-13 16:04 UTC, wolfsage commented on imap/mailbox.c
> +                xunlink(srcname);
Same here

2025-02-13 16:04 UTC, wolfsage commented on lib/cyrusdb_quotalegacy.c
> -                             fname);
Same here

2025-02-13 16:04 UTC, wolfsage commented on lib/xunlink.h
>   **/
This should also be adjusted to say that the function will return 0 for ENOENT instead of -1

2025-02-13 22:50 UTC, elliefm commented on imap/append.c
> -        if (xunlink(p) != 0) {
You're correct about the changed behaviour, but I think the changed behaviour is what we really want here.

Like, I suspect the lack of an exception for ENOENT in this case originally was an oversight.  This suspicion is based on the fairly cavalier way we've used unlink elsewhere in the code.  I think the places with ENOENT exceptions were added reactively and individually after some excess logging was annoying, rather than systematically and deliberately.  In situations like this where the stage file probably always exists when we try to remove it, we wouldn't have had any log noise about it not existing to silence.

I guess the way to find out would be to see if we're currently ever logging this ENOENT in practice.  If we are, it hasn't annoyed us and maybe we do want it; if we aren't, that would explain why we never got annoyed enough to add an exception for it.

Though it's also notable that we don't record any kind of error when _any_ unlink failure happens here, we just log and move on.  This also makes me think we don't really care much in the moment whether the unlink succeeds or not, we just log in case we need to know what happened later if we find some file still lying around.  In the case of an ENOENT, there won't be any files still lying around to need explaining.

2025-02-13 22:52 UTC, elliefm commented on lib/xunlink.h
>   **/
Ahh yeah good catch!

2025-02-13 22:55 UTC, elliefm commented on imap/mailbox.c
> +                xunlink(srcname);
Same thinking as the earlier case -- we didn't care about any unlink failure except to log it, and we don't think ENOENT is worth logging because the end state is the state we were trying to reach by unlinking

2025-02-13 23:00 UTC, elliefm commented on lib/cyrusdb_quotalegacy.c
> -                             fname);
This one is actually a meaningful behaviour change and not just a logging change, since we used to set `r = CYRUS_DBERROR` for ENOENT and with this change we'll ignore it.  I believe it's what we want though.

I guess this is another one where we could look for whether we ever log ENOENT here.  If it never happens in practice, then we never returned an error on this case, and perhaps the lack of an ENOENT exception was another oversight.  If we have been logging it, and haven't been annoyed by it, then maybe we do want it after all.  Perhaps we don't even use the quotalegacy db format, idk.

2025-02-14 01:00 UTC, elliefm commented on lib/xunlink.h
>   **/
I've rewritten this comment quite a bit, what do you think?

2025-02-14 02:16 UTC, elliefm commented on lib/xunlink.h
>   **/
It would actually be more in keeping with errno's usual behaviour to reset it to its previous value rather than 0 when ENOENT is detected (since a syscall that succeeds does not change errno at all).  I don't think it matters much in practice, but I'm overthinking the details now.

2025-02-14 17:09 UTC, wolfsage approved these changes

2025-02-14 17:09 UTC, wolfsage commented on imap/append.c
> -        if (xunlink(p) != 0) {
Yeah I'm not sure. Maybe someone who knows these bits of code better can comment. It feels like "We're cleaning up staging files. The file *should* exist." and in later ones we're cleaning up other files that *should* exist also.

I won't block the review MR, I'm just... uncomfortable unless we're really sure this is right

2025-03-06 23:18 UTC, merged